/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './resources/**/*.blade.php',
    './resources/**/*.js',
  ],
  theme: {
    extend: {
      keyframes: {
        'fade-in-up': {
          '0%': {
            opacity: '0',
            transform: 'translateY(16px)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0)',
          },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.4s cubic-bezier(0.23, 1, 0.32, 1) both',
      },
      colors: {
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#434655',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'outline': '#737686',
        'outline-variant': '#c3c6d7',
        'surface-tint': '#0053db',
        'primary': '#004ac6',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'inverse-primary': '#b4c5ff',
        'secondary': '#505f76',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'on-secondary-container': '#54647a',
        'tertiary': '#943700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bc4800',
        'on-tertiary-container': '#ffede6',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
        'success-green': '#22C55E',
        'warning-amber': '#F59E0B',
        'danger-red': '#EF4444',
        'surface-border': '#E2E8F0',
        'text-muted': '#64748B',
        'surface-neutral': '#F8FAFC',
        'border-hairline': '#E2E8F0',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'component-gap': '12px',
        'section-gap': '1.5rem',
        'grid-margin': '24px',
        'gutter': '16px',
        'card-gap': '12px',
        'container-margin': '1rem',
        'table-cell-padding': '12px',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'headline-h2': ['Inter'],
        'headline-h3': ['Inter'],
        'body-main': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-sm': ['Inter'],
        'label-xs': ['Inter'],
        'kpi-large': ['Inter'],
        'kpi-value': ['Inter'],
        'data-mono': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-h2': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-h3': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-main': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-xs': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'kpi-large': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'kpi-value': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
